/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"Create linked objects of your devices with a self-defined structure": {
		"en": "Create linked objects (datapoints) of your devices with a self-defined structure",
		"de": "Erstelle verlinkte Objekte deiner Geräte mit einer selbst definierten Struktur",
		"ru": "Создавайте связанные объекты ваших устройств с самоопределяемой структурой",
		"pt": "Crie objetos vinculados de seus dispositivos com uma estrutura autodefinida",
		"nl": "Maak gekoppelde objecten van uw apparaten met een zelf gedefinieerde structuur",
		"fr": "Créez des objets liés de vos appareils avec une structure auto-définie",
		"it": "Crea oggetti collegati dei tuoi dispositivi con una struttura auto-definita",
		"es": "Cree objetos vinculados de sus dispositivos con una estructura autodefinida",
		"pl": "Twórz połączone obiekty swoich urządzeń z samodzielnie zdefiniowaną strukturą",
		"zh-cn": "使用自定义结构创建设备的链接对象"
	},
	"linkeddevices adapter settings": {
		"en": "Adapter settings for linkeddevices",
		"de": "Adaptereinstellungen für linkeddevices",
		"ru": "Настройки адаптера linkeddevices",
		"pt": "Configurações do adaptador para linkeddevices",
		"nl": "Adapterinstellingen voor linkeddevices",
		"fr": "Paramètres d'adaptateur pour linkeddevices",
		"it": "Impostazioni dell'adattatore per linkeddevices",
		"es": "Ajustes del adaptador para linkeddevices",
		"pl": "Ustawienia adaptera dla linkeddevices",
		"zh-cn": "linkeddevices的适配器设置"
	},
	"delete objects that are no longer linked": {
		"en": "delete objects that are no longer linked",
		"de": "Objekte löschen, die nicht mehr verlinkt sind",
		"ru": "удалить объекты, которые больше не связаны",
		"pt": "excluir objetos que não estão mais vinculados",
		"nl": "objecten verwijderen die niet langer zijn gekoppeld",
		"fr": "supprimer des objets qui ne sont plus liés",
		"it": "elimina oggetti che non sono più collegati",
		"es": "eliminar objetos que ya no están vinculados",
		"pl": "usuń obiekty, które nie są już połączone",
		"zh-cn": "删除不再链接的对象"
	},
	"composite id of linked object": {
		"en": "composite id of linked object",
		"de": "Zusammengesetze Id des verlinkten Objektes",
		"ru": "Составной идентификатор связанного объекта",
		"pt": "ID composta do objeto vinculado",
		"nl": "samengestelde ID van gekoppeld object",
		"fr": "ID composite d'objet lié",
		"it": "ID composito dell'oggetto collegato",
		"es": "ID compuesto del objeto vinculado",
		"pl": "id złożony połączonego obiektu",
		"zh-cn": "链接对象的复合id"
	},
	"name of linked object": {
		"en": "name of linked object",
		"de": "Name des verlinkten Objekts",
		"ru": "Название связанного объекта",
		"pt": "nome do objeto vinculado",
		"nl": "naam van gekoppeld object",
		"fr": "nom de l'objet lié",
		"it": "nome dell'oggetto collegato",
		"es": "nombre del objeto vinculado",
		"pl": "nazwa połączonego obiektu",
		"zh-cn": "链接对象的名称"
	},
	"is linked": {
		"en": "is linked",
		"de": "verlinkt",
		"ru": "Связан",
		"pt": "está associado",
		"nl": "is gelinkt",
		"fr": "est lié",
		"it": "è collegato",
		"es": "está vinculado",
		"pl": "jest połączone",
		"zh-cn": "已连接"
	},
	"linked with": {
		"en": "linked with",
		"de": "verlinkt mit",
		"ru": "Связан с",
		"pt": "ligado com",
		"nl": "gelinkt met",
		"fr": "lié à",
		"it": "collegato con",
		"es": "Vinculado con",
		"pl": "połączony z",
		"zh-cn": "与连接"
	},
	"expert settings for linked object with type '%s'": {
		"en": "expert settings for linked object with type '%s'",
		"de": "Experteneinstellungen für verlinktes Objekt vom Typ '%s'",
		"ru": "Экспертные настройки для связанного объекта с типом '%s'",
		"pt": "configurações de especialista para objeto vinculado com o tipo '%s'",
		"nl": "expertinstellingen voor gekoppeld object met type '%s'",
		"fr": "paramètres experts pour un objet lié de type '%s'",
		"it": "impostazioni avanzate per l'oggetto collegato con tipo '%s'",
		"es": "Configuraciones expertas para objetos vinculados con tipo '%s'",
		"pl": "ustawienia eksperckie dla obiektu połączonego z typem '%s'",
		"zh-cn": "类型为'%s'的链接对象的专家设置"
	},
	"change unit '%s' to": {
		"en": "change unit '%s' to",
		"de": "Ändere Einheit '%s' in",
		"ru": "Изменить единицу измерения %s на",
		"pt": "mudar a unidade '%s' para",
		"nl": "verander eenheid '%s' in",
		"fr": "remplacez l'unité '%s' par",
		"it": "cambia unità '%s' a",
		"es": "cambia la unidad '%s' a",
		"pl": "zmień jednostkę „%s” na",
		"zh-cn": "将单位“%s”更改为"
	},
	"prefix for id of linked object": {
		"en": "prefix for id of linked object",
		"de": "Präfix für ID des verlinkten Objektes",
		"ru": "Префикс для идентификатора связанного объекта",
		"pt": "prefixo para id do objeto vinculado",
		"nl": "voorvoegsel voor id van gekoppeld object",
		"fr": "préfixe pour l'identifiant de l'objet lié",
		"it": "prefisso per l'id dell'oggetto collegato",
		"es": "prefijo para id del objeto vinculado",
		"pl": "prefiks dla id połączonego obiektu",
		"zh-cn": "链接对象的id的前缀"
	},
	"id of linked object": {
		"en": "id of linked object",
		"de": "ID des verlinkten Objekts",
		"ru": "Идентификатор связанного объекта",
		"pt": "ID do objeto vinculado",
		"nl": "id van gekoppeld object",
		"fr": "id de l'objet lié",
		"it": "id di oggetto collegato",
		"es": "Id del objeto vinculado",
		"pl": "id połączonego obiektu",
		"zh-cn": "链接对象的id"
	},
	"only numbers and math operators allowed for read only object": {
		"en": "not allowed signs!<br>Only numbers an math operatorsare allowed! Input must start with math operator.<br><br>Allowed operators: + - / * , . ( )",
		"de": "Zeichen nicht erlaubt! <br> Nur Zahlen und mathematische Operatoren sind erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen. <br> <br> Zulässige Operatoren: + - / *,. ()",
		"ru": "Запрещенные символы! <br> Разрешены только цифры и математические операторы! Поле должно начинаться с математического оператора. <br> <br> Допустимые операторы: + - / *,. ()",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos são permitidos! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: + - / *,. ()",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators zijn toegestaan! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: + - / *,. ()",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés! La saisie doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: + - / *,. ()",
		"it": "segni non consentiti! <br> Sono consentiti solo numeri e operatori matematici! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: + - / *,. ()",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten operadores de números y matemáticas! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: + - / *,. ()",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne są dozwolone! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: + - / *,. ()",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符！输入必须以数学运算符开头。<br> <br>允许的运算符：+  -  / * ,. （）"
	},
	"only numbers and math operators allowed": {
		"en": "not allowed signs!<br>Only numbers an math operatorsare allowed! Input must start with math operator.<br><br>Allowed operators: / * , .",
		"de": "Zeichen nicht erlaubt! <br> Nur Zahlen und mathematische Operatoren sind erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen. <br> <br> Zulässige Operatoren: / *,.",
		"ru": "Запрещенные символы! <br> Разрешены только цифры и математические операторы! Поле должно начинаться с математического оператора. <br> <br> Разрешенные операторы: / *,.",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos são permitidos! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: / *,.",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators zijn toegestaan! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: / *,.",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés! La saisie doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: / *,.",
		"it": "segni non consentiti! <br> Sono consentiti solo numeri e operatori matematici! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: / *,.",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten operadores de números y matemáticas! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: / *,.",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne są dozwolone! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: / *,.",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符！输入必须以数学运算符开头。<br> <br>允许的运算符：/ * ,."
	},
	"only numbers and math operators allowed2": {
		"en": "not allowed signs!<br>Only numbers an math operatorsare allowed! Input must start with math operator.<br><br>Allowed operators: / *",
		"de": "Zeichen nicht erlaubt! <br> Nur Zahlen und mathematische Operatoren sind erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen. <br> <br> Zulässige Operatoren: / *",
		"ru": "Запрещенные символы! <br> Разрешены только цифры и математические операторы! Поле должно начинаться с математического оператора. <br> <br> Разрешенные операторы: / *",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos são permitidos! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: / *",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators zijn toegestaan! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: / *",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés! La saisie doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: / *",
		"it": "segni non consentiti! <br> Sono consentiti solo numeri e operatori matematici! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: / *",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten operadores de números y matemáticas! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: / *",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne są dozwolone! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: / *",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符！输入必须以数学运算符开头。<br> <br>允许的运算符：/ *"
	},
	"max. number of decimal places": {
		"en": "max. number of decimal places",
		"de": "max. Anzahl der Nachkommastellen",
		"ru": "Максимальное количество знаков после запятой",
		"pt": "max. número de casas decimais",
		"nl": "max. aantal decimalen",
		"fr": "max. nombre de décimales",
		"it": "max. numero di cifre decimali",
		"es": "max. número de decimales",
		"pl": "max. liczba miejsc dziesiętnych",
		"zh-cn": "最大。小数位数"
	},
	"only numbers allowed": {
		"en": "only numbers allowed",
		"de": "Nur Nummern sind als Eingabe erlaubt!",
		"ru": "Разрешены только цифры",
		"pt": "somente números permitidos",
		"nl": "alleen cijfers toegestaan",
		"fr": "seuls les nombres autorisés",
		"it": "solo numeri consentiti",
		"es": "solo números permitidos",
		"pl": "dozwolone są tylko liczby",
		"zh-cn": "只允许数字"
	},
	"calculation for 'read' object": {
		"en": "calculation for 'read' object",
		"de": "Umrechnung für verlinktes 'read' Objekt",
		"ru": "Выражение для «read-only» объекта",
		"pt": "cálculo para objeto 'read'",
		"nl": "berekening voor 'lees' object",
		"fr": "calcul pour objet 'lu'",
		"it": "calcolo per oggetto 'lettura'",
		"es": "cálculo para el objeto 'leer'",
		"pl": "obliczanie obiektu „czytaj”",
		"zh-cn": "计算'读'对象"
	},
	"calculation for linked object": {
		"en": "calculation for linked object",
		"de": "Umrechnung für verlinktes Objekt",
		"ru": "Выражение для связанного объекта",
		"pt": "cálculo para objeto vinculado",
		"nl": "berekening voor gekoppeld object",
		"fr": "calcul pour objet lié",
		"it": "calcolo per oggetto collegato",
		"es": "cálculo para objeto vinculado",
		"pl": "obliczenia dla połączonego obiektu",
		"zh-cn": "链接对象的计算"
	},
	"number": {
		"en": "number",
		"de": "Zahl",
		"ru": "Число",
		"pt": "número",
		"nl": "getal",
		"fr": "nombre",
		"it": "Numero",
		"es": "numero",
		"pl": "numer",
		"zh-cn": "数"
	},
	"not allowed chars for Id": {
		"en": "not allowed chars for Id!<br><br>Not Allowed chars: %s",
		"de": "Zeichen für Id nicht erlaubt!<br><br> Nicht erlaubte Zeichen: %s ",
		"ru": "недопустимые символы для Id!<br><br> Запрещенные символы: %s ",
		"pt": "não são permitidos caracteres para o Id!<br><br> Caracteres não permitidos: %s ",
		"nl": "niet toegestane tekens voor Id!<br><br> Niet toegestane tekens: %s ",
		"fr": "caractères non autorisés pour l'Id!<br><br> Caractères non autorisés: %s ",
		"it": "caratteri non consentiti per Id!<br><br> Caratteri non consentiti: %s ",
		"es": "No se permiten caracteres para Id.<br><br> Caracteres no permitidos: %s ",
		"pl": "niedozwolone znaki dla Id!<br><br> Niedozwolone znaki: %s ",
		"zh-cn": "不允许将字符用作ID！<br><br>不允许的字符：％s"
	},
	"do not convert": {
		"en": "do not convert",
		"de": "nicht umwandeln",
		"ru": "Не конвертировать",
		"pt": "não converter",
		"nl": "niet converteren",
		"fr": "ne pas convertir",
		"it": "non convertire",
		"es": "no convertir",
		"pl": "nie konwertuj",
		"zh-cn": "不要转换"
	},
	"convert linked object to type": {
		"en": "convert to type",
		"de": "Konvertiere in Typ",
		"ru": "Преобразовать в тип",
		"pt": "converter em tipo",
		"nl": "converteren naar type",
		"fr": "convertir en type",
		"it": "convertire in tipo",
		"es": "convertir a tipo",
		"pl": "przekonwertować na typ",
		"zh-cn": "转换为类型"
	},
	"condition 'true' for linked object": {
		"en": "condition 'true' for linked object",
		"de": "Bedingung 'true' für verlinktes Objekt",
		"ru": "Условие 'true' для связанного объекта",
		"pt": "condição 'true' para objeto vinculado",
		"nl": "voorwaarde 'waar' voor gekoppeld object",
		"fr": "condition 'true' pour objet lié",
		"it": "condizione 'true' per oggetto collegato",
		"es": "Condición 'true' para objeto vinculado",
		"pl": "warunek „prawda” dla połączonego obiektu",
		"zh-cn": "条件'true'表示链接对象"
	},
	"value if linked object is 'true'": {
		"en": "value if linked object is 'true'",
		"de": "Wert wenn verlinktes Objekt 'true' ist",
		"ru": "Значение, если связанный объект равен 'true'",
		"pt": "valor se o objeto vinculado for 'verdadeiro'",
		"nl": "waarde als gekoppeld object 'waar' is",
		"fr": "valeur si l'objet lié est 'true'",
		"it": "valore se l'oggetto collegato è 'vero'",
		"es": "valor si el objeto vinculado es 'verdadero'",
		"pl": "wartość, jeśli powiązany obiekt jest „prawdziwy”",
		"zh-cn": "链接对象为'true'时的值"
	},
	"value if linked object is 'false'": {
		"en": "value if linked object is 'false'",
		"de": "Wert wenn verlinktes Objekt 'false' ist",
		"ru": "Значение, если связанный объект имеет значение 'false'",
		"pt": "valor se o objeto vinculado for 'falso'",
		"nl": "waarde als gekoppeld object 'false' is",
		"fr": "valeur si l'objet lié est 'false'",
		"it": "valore se l'oggetto collegato è 'falso'",
		"es": "valor si el objeto vinculado es 'falso'",
		"pl": "wartość, jeśli połączony obiekt jest „fałszywy”",
		"zh-cn": "链接对象为'false'时的值"
	},
	"change min '%s' to": {
		"en": "change min '%s' to",
		"de": "Ändere min '%s' in",
		"ru": "Изменить min '%s' на",
		"pt": "altere min '%s' para",
		"nl": "verander min '%s' in",
		"fr": "remplacez min '%s' par",
		"it": "cambia min '%s' in",
		"es": "cambiar min '%s' a",
		"pl": "zmień min '%s' na",
		"zh-cn": "将min'％s'更改为"
	},
	"change max '%s' to": {
		"en": "change max '%s' to",
		"de": "Ändere max '%s' auf",
		"ru": "Изменить max '%s' на",
		"pt": "altere max '%s' para",
		"nl": "verander max '%s' in",
		"fr": "remplacez max '%s' par",
		"it": "modifica max '%s' a",
		"es": "cambiar max '%s' a",
		"pl": "zmień max '%s' na",
		"zh-cn": "将max'％s'更改为"
	},
	"only numbers and mathematical operators allowed as a condition": {
		"en": "not allowed signs!<br>Only numbers and mathematical operators allowed as a condition! Input must start with math operator.<br><br>Allowed operators: = != > < >= <=",
		"de": "Zeichen nicht erlaubt!<br>Nur Zahlen und mathematische Operatoren als Bedingung erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen.<br><br>Zulässige Operatoren: = != > < >= <=",
		"ru": "Запрещенные символы! <br> В качестве условия допускаются только числа и математические операторы! Ввод должен начинаться с математического оператора. <br> <br> Разрешенные операторы: =! => <> = <=",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos permitidos como condição! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: =! => <> = <=",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators toegestaan ​​als voorwaarde! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: =! => <> = <=",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés comme condition! L'entrée doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: =! => <> = <=",
		"it": "segni non consentiti! <br> Solo numeri e operatori matematici ammessi come condizione! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: =! => <> = <=",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten números y operadores matemáticos como condición! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: =! => <> = <=",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne dozwolone jako warunek! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: =! => <> = <=",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符作为条件！输入必须以数学运算符开头。<br> <br>允许的运算符：=！=> <> = <="
	},
	"conditions string": {
		"en": "conditions string",
		"de": "Zeichenkette mit Bedingungen",
		"ru": "Условия",
		"pt": "condições de string",
		"nl": "voorwaarden string",
		"fr": "conditions chaîne",
		"it": "stringa di condizioni",
		"es": "cadena de condiciones",
		"pl": "warunki ciąg",
		"zh-cn": "条件字符串"
	},
	"conditions multi": {
		"en": "conditions multi",
		"de": "Werteliste mit Bedingungen",
		"ru": "Условия (несколько)",
		"pt": "condições multi",
		"nl": "voorwaarden multi",
		"fr": "conditions multi",
		"it": "condizioni multi",
		"es": "condiciones multi",
		"pl": "warunki multi",
		"zh-cn": "条件多"
	},
	"string": {
		"en": "string",
		"de": "Zeichenkette",
		"ru": "Строка",
		"pt": "string",
		"nl": "Tekenreeks",
		"fr": "chaîne",
		"it": "stringa",
		"es": "cadena de caracteres",
		"pl": "strunowy",
		"zh-cn": "串"
	},
	"boolean": {
		"en": "boolean",
		"de": "Logikwert",
		"ru": "Логическая переменная",
		"pt": "valor lógico",
		"nl": "boolean",
		"fr": "booléen",
		"it": "Booleano",
		"es": "booleano",
		"pl": "boolean",
		"zh-cn": "布尔"
	},
	"multi": {
		"en": "multistate",
		"de": "Werteliste",
		"ru": "Перечисление",
		"pt": "lista de valores",
		"nl": "waardenlijst",
		"fr": "liste de valeurs",
		"it": "Multistate",
		"es": "lista de valores",
		"pl": "multistate",
		"zh-cn": "多态"
	},
	"enabled": {
		"en": "enabled",
		"de": "Aktiviert",
		"ru": "активно",
		"pt": "ativado",
		"nl": "ingeschakeld",
		"fr": "activée",
		"it": "abilitato",
		"es": "activado",
		"pl": "włączony",
		"zh-cn": "启用"
	},
	"active": {
		"en": "active",
		"de": "aktiv",
		"ru": "активно",
		"pt": "ativo",
		"nl": "actief",
		"fr": "actif",
		"it": "Attivo",
		"es": "activo",
		"pl": "aktywny",
		"zh-cn": "激活"
	},
	"Cancel": {
		"en": "Cancel",
		"de": "Abbrechen",
		"ru": "Отмена",
		"pt": "Cancelar",
		"nl": "Annuleren",
		"fr": "Annuler",
		"it": "Annulla",
		"es": "Cancelar",
		"pl": "Anuluj",
		"zh-cn": "取消"
	},
	"Settings": {
		"en": "Settings",
		"de": "Einstellungen",
		"ru": "Настройки",
		"pt": "Configurações",
		"nl": "instellingen",
		"fr": "Paramètres",
		"it": "impostazioni",
		"es": "Configuración",
		"pl": "Ustawienia",
		"zh-cn": "设置"
	},
	"Settings for %s": {
		"en": "Settings for %s",
		"de": "Einstellungen für %s",
		"ru": "Настройки для %s",
		"pt": "Configurações para %s",
		"nl": "Instellingen voor %s",
		"fr": "Paramètres pour %s",
		"it": "Impostazioni per %s",
		"es": "Configuraciones para %s",
		"pl": "Ustawienia dla %s",
		"zh-cn": "%s的设置"
	},
	"Storage of %s": {
		"en": "Storage of <span class=\"name\">%s</span>",
		"de": "Einstellungen von <span class=\"name\">%s</span>",
		"ru": "Настройки для <span class=\"name\">%s</span>",
		"pt": "História de <span class=\"name\">%s</span>",
		"nl": "Opslag van <span class=\"name\">%s</span>",
		"fr": "Stockage de <span class=\"name\">%s</span>",
		"it": "Memorizzazione di %s",
		"es": "Configuraciones de <span class=\"name\">%s</span>",
		"pl": "Przechowywanie <span class=\"name\"> %s </span>",
		"zh-cn": "存储<span class=\"name\">%s</span>"
	},
	"Save": {
		"en": "Save",
		"de": "Speichern",
		"ru": "Сохранить",
		"pt": "Gravar",
		"nl": "Opslaan",
		"fr": "sauvegarder",
		"it": "Salvare",
		"es": "Grabar",
		"pl": "Zapisać",
		"zh-cn": "保存"
	},
	"Table": {
		"en": "Table",
		"de": "Tabelle",
		"ru": "Таблица",
		"pt": "Tabela",
		"nl": "Tabel",
		"fr": "Table",
		"it": "tabella",
		"es": "Tabla",
		"pl": "Stół",
		"zh-cn": "表"
	},
	"Chart": {
		"en": "Chart",
		"de": "Grafik",
		"ru": "График",
		"pt": "Gráfico",
		"nl": "tabel",
		"fr": "Graphique",
		"it": "diagramma",
		"es": "Gráfico",
		"pl": "Wykres",
		"zh-cn": "图表"
	},
	"Are you sure? Changes are not saved.": {
		"en": "Are you sure? Changes are not saved.",
		"de": "Sind Sie sicher? Die Änderungen sind nicht gespeichert.",
		"ru": "Изменения не сохранены. Всё равно закрыть?",
		"pt": "Você tem certeza? As alterações não estão gravadas.",
		"nl": "Weet je het zeker? Wijzigingen worden niet opgeslagen.",
		"fr": "Êtes-vous sûr? Les modifications ne sont pas enregistrées.",
		"it": "Sei sicuro? Le modifiche non verranno salvate.",
		"es": "¿Estás seguro? Los cambios no se guardan.",
		"pl": "Jesteś pewny? Zmiany nie są zapisywane.",
		"zh-cn": "你确定吗？更改未保存。"
	},
	"Please confirm": {
		"en": "Please confirm",
		"de": "Bitte bestätigen",
		"ru": "Пожалуйста подтвердите",
		"pt": "Por favor confirme",
		"nl": "Bevestig alstublieft",
		"fr": "Veuillez confirmer",
		"it": "Si prega di confermare",
		"es": "Por favor, confirme",
		"pl": "Proszę potwierdzić", "zh-cn": "请确认"
	},
	"value if object is 'true'": {
		"en": "value if object is 'true'",
		"de": "Wert wenn Objekt 'true' ist",
		"ru": "значение, если объект равен 'true'",
		"pt": "valor se o objeto for 'verdadeiro'",
		"nl": "waarde als object 'waar' is",
		"fr": "valeur si l'objet est 'true'",
		"it": "valore se l'oggetto è 'vero'",
		"es": "valor si el objeto es 'verdadero'",
		"pl": "wartość, jeśli obiekt jest „prawdziwy”",
		"zh-cn": "对象为'true'时的值"
	},
	"value if object is 'false'": {
		"en": "value if object is 'false'",
		"de": "Wert wenn Objekt 'false' ist",
		"ru": "значение, если объект 'false'",
		"pt": "valor se o objeto for 'falso'",
		"nl": "waarde als object 'false' is",
		"fr": "valeur si l'objet est 'false'",
		"it": "valore se l'oggetto è 'falso'",
		"es": "valor si el objeto es 'falso'",
		"pl": "wartość, jeśli obiekt jest „fałszywy”",
		"zh-cn": "对象为'false'时的值"
	},
	"settings can only be adjusted in the object to which it is linked!": {
		"en": "settings can only be adjusted in the object to which it is linked!",
		"de": "Einstellungen können nur in dem Objekt vorgenommen werden, mit dem es verlinkt ist!",
		"ru": "Настройки можно изменить только в том объекте, с которым он связан!",
		"pt": "configurações só podem ser ajustadas no objeto ao qual está vinculado!",
		"nl": "instellingen kunnen alleen worden aangepast in het object waaraan het is gekoppeld!",
		"fr": "les réglages ne peuvent être ajustés que dans l'objet auquel il est lié!",
		"it": "le impostazioni possono essere modificate solo nell'oggetto a cui è collegato!",
		"es": "La configuración solo se puede ajustar en el objeto al que está vinculado.",
		"pl": "ustawienia można regulować tylko w obiekcie, z którym jest połączony!",
		"zh-cn": "设置只能在与其链接的对象中进行调整！"
	},
	"Select": {
		"en": "Select",
		"de": "Auswählen",
		"ru": "Выбрать",
		"pt": "Selecione",
		"nl": "kiezen",
		"fr": "Sélectionner",
		"it": "Selezionare",
		"es": "Seleccione",
		"pl": "Wybierz",
		"zh-cn": "选择"
	},
	"assign link": {
		"en": "assign link",
		"de": "Link zuweisen",
		"ru": "Назначить связь",
		"pt": "atribuir link",
		"nl": "link toewijzen",
		"fr": "attribuer un lien",
		"it": "assegna il collegamento",
		"es": "asignar enlace",
		"pl": "przypisz link",
		"zh-cn": "分配链接"
	},
	"remove link": {
		"en": "remove link",
		"de": "Link entfernen",
		"ru": "Удалить связь",
		"pt": "remover link",
		"nl": "link verwijderen",
		"fr": "supprimer le lien",
		"it": "rimuovi link",
		"es": "remover enlace",
		"pl": "usuń link",
		"zh-cn": "删除链接"
	},
	"Overview of all linked objects": {
		"en": "Overview of all linked objects",
		"de": "Übersicht aller verlinkten Objekte",
		"ru": "Обзор связанных объектов",
		"pt": "Visão geral de todos os objetos vinculados",
		"nl": "Overzicht van alle gekoppelde objecten",
		"fr": "Vue d'ensemble de tous les objets liés",
		"it": "Panoramica di tutti gli oggetti collegati",
		"es": "Resumen de todos los objetos vinculados",
		"pl": "Przegląd wszystkich połączonych obiektów",
		"zh-cn": "所有链接对象的概述"
	},
	"name": {
		"en": "name",
		"de": "Name",
		"ru": "Имя",
		"pt": "nome",
		"nl": "Naam",
		"fr": "prénom",
		"it": "nome",
		"es": "nome",
		"pl": "Nazwa",
		"zh-cn": "名称"
	},
	"browse the table": {
		"en": "browse the table",
		"de": "Tabelle durchsuchen",
		"ru": "Просмотреть таблицу",
		"pt": "navegue pela mesa",
		"nl": "blader door de tafel",
		"fr": "parcourir la table",
		"it": "sfoglia il tavolo",
		"es": "navegar por la mesa",
		"pl": "przeglądaj stół",
		"zh-cn": "浏览表格"
	},
	"link to an already linked object of the same instance is not possible!": {
		"en": "link to an already linked object of the same instance is not possible!",
		"de": "Eine Verlinkung zu einem bereits verlinkten Objekt derselben Instanz ist nicht möglich!",
		"ru": "Ссылка на уже связанный объект того же экземпляра невозможна!",
		"pt": "link para um objeto já vinculado da mesma instância não é possível!",
		"nl": "link naar een reeds gekoppeld object van dezelfde instantie is niet mogelijk!",
		"fr": "un lien vers un objet déjà lié de la même instance n'est pas possible!",
		"it": "il collegamento a un oggetto già collegato della stessa istanza non è possibile!",
		"es": "¡El enlace a un objeto ya enlazado de la misma instancia no es posible!",
		"pl": "link do już połączonego obiektu tej samej instancji nie jest możliwy!",
		"zh-cn": "链接到同一实例的已链接对象是不可能的！"
	},
	"the selected object is already linked with '%s'!": {
		"en": "the selected object is already linked with '%s'!",
		"de": "das ausgewählte Objekt ist bereits mit '%s' verlinkt!",
		"ru": "Выбранный объект уже связан с ''%s'!",
		"pt": "o objeto selecionado já está vinculado a '%s'!",
		"nl": "het geselecteerde object is al gekoppeld aan '%s'!",
		"fr": "l'objet sélectionné est déjà lié à '%s'!",
		"it": "l'oggetto selezionato è già collegato con '%s'!",
		"es": "el objeto seleccionado ya está vinculado con '%s'!",
		"pl": "wybrany obiekt jest już powiązany z '%s'!",
		"zh-cn": "所选对象已与'％s'链接!"
	},
	"the selected object is of type '%s'.<br>The linked object needs an object of type '%s'!": {
		"en": "the selected object is of type '%s'.<br>The linked object needs an object of type '%s'!",
		"de": "Das ausgewählte Objekt ist vom Typ '%s'.<br>Das verlinkte Objekt benötigt aber ein Objekt vom Typ '%s'!",
		"ru": "Выбранный объект имеет тип '%s' \"'.<br>Связанному объекту нужен объект типа '%s'!",
		"pt": "o objeto selecionado é do tipo '%s'.<br>O objeto vinculado precisa de um objeto do tipo '%s'!",
		"nl": "het geselecteerde object is van het type '%s'.<br>Het gekoppelde object heeft een object van het type '%s' nodig!",
		"fr": "l'objet sélectionné est de type '%s'.<br>L'objet lié a besoin d'un objet de type '%s'!",
		"it": "l'oggetto selezionato è di tipo '%s'.<br>L'oggetto collegato ha bisogno di un oggetto di tipo '%s'!",
		"es": "El objeto seleccionado es de tipo '%s'.<br>El objeto vinculado necesita un objeto de tipo '%s'!",
		"pl": "wybrany obiekt jest typu '%s'.<br>Połączony obiekt potrzebuje obiektu typu '%s'!",
		"zh-cn": "所选对象的类型为'％s'。链接对象需要一个'％s'类型的对象！"
	},
	"Error": {
		"en": "Error",
		"de": "Fehler",
		"ru": "Ошибка",
		"pt": "Erro",
		"nl": "Fout",
		"fr": "Erreur",
		"it": "Errore",
		"es": "Error",
		"pl": "Błąd",
		"zh-cn": "错误"
	},
	"Via 'Settings' button in the menu 'Object' you can create a new linked object.": {
		"en": "Via 'Settings' button in the menu 'Object' you can create a new linked object.",
		"de": "Über die Schaltfläche 'Einstellungen' im Menü 'Objekt' kann ein neues verlinktes Objekt erstellt werden.",
		"ru": "С помощью кнопки «Настройки» в меню «Объекты» вы можете создать новый связанный объект.",
		"pt": "Através do botão 'Configurações' no menu 'Objeto' você pode criar um novo objeto vinculado.",
		"nl": "Via de knop 'Instellingen' in het menu 'Object' kunt u een nieuw gekoppeld object maken.",
		"fr": "Via le bouton 'Paramètres' du menu 'Objet', vous pouvez créer un nouvel objet lié.",
		"it": "Tramite il pulsante \"Impostazioni\" nel menu \"Oggetto\" è possibile creare un nuovo oggetto collegato.",
		"es": "A través del botón 'Configuración' en el menú 'Objeto' puede crear un nuevo objeto vinculado.",
		"pl": "Za pomocą przycisku „Ustawienia” w menu „Obiekt” możesz utworzyć nowy połączony obiekt.",
		"zh-cn": "通过菜单“对象”中的“设置”按钮，您可以创建新的链接对象。"
	},
	"no linked objects available": {
		"en": "no linked objects available",
		"de": "Keine verlinkten Objekte vorhanden",
		"ru": "Нет связанных объектов",
		"pt": "não há objetos vinculados disponíveis",
		"nl": "geen gekoppelde objecten beschikbaar",
		"fr": "aucun objet lié disponible",
		"it": "nessun oggetto collegato disponibile",
		"es": "no hay objetos vinculados disponibles",
		"pl": "brak dostępnych połączonych obiektów",
		"zh-cn": "没有可用的链接对象"
	},
	"duration": {
		"en": "duration",
		"de": "Dauer",
		"ru": "Продолжительность",
		"pt": "duração",
		"nl": "looptijd",
		"fr": "durée",
		"it": "durata",
		"es": "duración",
		"pl": "Trwanie",
		"zh-cn": "持续时间"
	},
	"conversion in seconds": {
		"en": "conversion in seconds",
		"de": "Umrechnung in Sekunden",
		"ru": "Преобразование в секундах",
		"pt": "conversão em segundos",
		"nl": "conversie in seconden",
		"fr": "conversion en quelques secondes",
		"it": "conversione in secondi",
		"es": "conversión en segundos",
		"pl": "konwersja w sekundach",
		"zh-cn": "转换为秒"
	},
	"display format of the duration": {
		"en": "display format of the duration",
		"de": "Anzeigeformat der Dauer",
		"ru": "Формат отображения длительности",
		"pt": "formato de exibição da duração",
		"nl": "weergaveformaat van de duur",
		"fr": "format d'affichage de la durée",
		"it": "visualizza il formato della durata",
		"es": "Formato de visualización de la duración.",
		"pl": "format wyświetlania czasu trwania",
		"zh-cn": "显示格式的持续时间"
	},
	"prefix string": {
		"en": "prefix string",
		"de": "vorangestellte Zeichenfolge",
		"ru": "префиксная строка",
		"pt": "prefixo de string",
		"nl": "voorvoegsel tekenreeks",
		"fr": "chaîne de préfixe",
		"it": "stringa prefisso",
		"es": "cadena de prefijo",
		"pl": "przedrostek ciąg",
		"zh-cn": "前缀字符串"
	},
	"suffix string": {
		"en": "suffix string",
		"de": "nachgestellte Zeichenfolge",
		"ru": "Строка суффикса",
		"pt": "string de sufixo",
		"nl": "achtervoegsel string",
		"fr": "chaîne de suffixe",
		"it": "stringa del suffisso",
		"es": "cadena de sufijo",
		"pl": "łańcuch sufiksów",
		"zh-cn": "后缀字符串"
	},
	"display format of the datetime": {
		"en": "display format of the datetime",
		"de": "Anzeigeformat der Datum / Uhrzeit",
		"ru": "Формат отображения даты и времени",
		"pt": "formato de exibição da data e hora",
		"nl": "weergaveformaat van de datetime",
		"fr": "format d'affichage du datetime",
		"it": "visualizza il formato del datetime",
		"es": "Formato de visualización de la fecha y hora.",
		"pl": "format wyświetlania daty / godziny",
		"zh-cn": "显示日期时间的格式"
	},
	"datetime": {
		"en": "datetime",
		"de": "Datum / Uhrzeit",
		"ru": "Дата и время",
		"pt": "data hora",
		"nl": "datum Tijd",
		"fr": "date / heure",
		"it": "appuntamento",
		"es": "fecha y hora",
		"pl": "datetime",
		"zh-cn": "约会时间"
	},
	"conversion in unix timestamp (seconds)": {
		"en": "conversion in unix timestamp (seconds)",
		"de": "Umrechung in Unixzeit (Sekunden)",
		"ru": "Преобразование в метку времени Unix (секунды)",
		"pt": "conversão em timestamp unix (segundos)",
		"nl": "conversie in unix-tijdstempel (seconden)",
		"fr": "conversion en timestamp unix (secondes)",
		"it": "conversione in unix timestamp (secondi)",
		"es": "Conversión en sello de tiempo Unix (segundos)",
		"pl": "konwersja w uniksowym znaczniku czasu (sekundy)",
		"zh-cn": "unix时间戳（秒）转换"
	},
	"string for 'true' of the linked object": {
		"en": "string for 'true' of the linked object",
		"de": "Zeichenkette für 'true' des verlinkten Objekts",
		"ru": "Строка для 'true' связанного объекта",
		"pt": "string para 'true' do objeto vinculado",
		"nl": "tekenreeks voor 'true' van het gekoppelde object",
		"fr": "chaîne pour 'true' de l'objet lié",
		"it": "stringa per \"true\" dell'oggetto collegato",
		"es": "cadena para 'verdadero' del objeto vinculado",
		"pl": "ciąg „true” połączonego obiektu",
		"zh-cn": "链接对象的“true”字符串"
	},
	"string for 'false' of the linked object": {
		"en": "string for 'false' of the linked object",
		"de": "Zeichenkette für 'false' des verlinkten Objekts",
		"ru": "Строка для 'false' связанного объекта",
		"pt": "string para 'false' do objeto vinculado",
		"nl": "tekenreeks voor 'false' van het gekoppelde object",
		"fr": "chaîne pour 'false' de l'objet lié",
		"it": "stringa per \"false\" dell'oggetto collegato",
		"es": "cadena para 'falso' del objeto vinculado",
		"pl": "ciąg dla „false” powiązanego obiektu",
		"zh-cn": "链接对象的“false”字符串"
	},
	"create a script with variables of all linked objects": {
		"en": "create a script with variables of all linked objects",
		"de": "Skript mit Variablen aller verlinkten Objekte erzeugen",
		"ru": "Создать скрипт с переменными всех связанных объектов",
		"pt": "criar um script com variáveis de todos os objetos vinculados",
		"nl": "maak een script met variabelen van alle gekoppelde objecten",
		"fr": "créer un script avec des variables de tous les objets liés",
		"it": "creare uno script con variabili di tutti gli oggetti collegati",
		"es": "crear un script con variables de todos los objetos vinculados",
		"pl": "utwórz skrypt ze zmiennymi wszystkich połączonych obiektów",
		"zh-cn": "使用所有链接对象的变量创建脚本"
	},
	"javascript adapter is not installed": {
		"en": "javascript adapter is not installed",
		"de": "Javascript Adapter ist nicht installiert",
		"ru": "Javascript адаптер не установлен",
		"pt": "adaptador de javascript não está instalado",
		"nl": "javascript-adapter is niet geïnstalleerd",
		"fr": "adaptateur javascript n'est pas installé",
		"it": "l'adattatore javascript non è installato",
		"es": "el adaptador de JavaScript no está instalado",
		"pl": "adapter javascript nie jest zainstalowany",
		"zh-cn": "未安装javascript适配器"
	},
	"attention": {
		"en": "attention",
		"de": "Achtung",
		"ru": "Внимание",
		"pt": "atenção",
		"nl": "aandacht",
		"fr": "attention",
		"it": "Attenzione",
		"es": "atención",
		"pl": "Uwaga",
		"zh-cn": "注意"
	},
	"After the script has been generated, the javascript adapter will be restarted!<br><br><br>Do you want to continue?": {
		"en": "After the script has been generated, the javascript adapter will be restarted!<br><br><br>Do you want to continue?",
		"de": "Nachdem das Skript generiert wurde, wird der Javascript Adapter neu gestartet! <br><br><br> Möchtest Du fortfahren?",
		"ru": "После того, как сценарий был сгенерирован, адаптер javascript будет перезапущен! <br><br><br> Вы хотите продолжить?",
		"pt": "Depois que o script for gerado, o adaptador de javascript será reiniciado! <br><br><br> Você quer continuar?",
		"nl": "Nadat het script is gegenereerd, wordt de JavaScript-adapter opnieuw gestart! <br><br><br> Wil je doorgaan?",
		"fr": "Une fois le script généré, l'adaptateur javascript sera redémarré! <br><br><br> Voulez-vous continuer?",
		"it": "Dopo che lo script è stato generato, l'adattatore javascript verrà riavviato! <br><br><br> Vuoi continuare?",
		"es": "Después de que se haya generado el script, se reiniciará el adaptador de JavaScript. <br><br><br> ¿Quieres continuar?",
		"pl": "Po wygenerowaniu skryptu adapter javascript zostanie ponownie uruchomiony! <br><br><br> Czy chcesz kontynuować?",
		"zh-cn": "生成脚本后，将重新启动javascript适配器！ <br><br><br>你想继续吗？"
	},
	"You like the adapter? Then support us with a small donation.": {
		"en": "You like the adapter? Then support the adapter developer (Scrounger) with a small donation.",
		"de": "Dir gefällt der Adapter? Dann unterstütze den Adapterentwickler (Scrounger) mit einer kleinen Spende.",
		"ru": "Вам нравится адаптер? Затем поддержите разработчика адаптера (Scrounger) с небольшим пожертвованием.",
		"pt": "Você gosta do adaptador? Depois, ofereça suporte ao desenvolvedor do adaptador (Scrounger) com uma pequena doação.",
		"nl": "Vind je de adapter leuk? Ondersteun vervolgens de adapterontwikkelaar (Scrounger) met een kleine donatie.",
		"fr": "Vous aimez l'adaptateur? Soutenez ensuite le développeur de l'adaptateur (Scrounger) avec un petit don.",
		"it": "Ti piace l'adattatore? Quindi supportare lo sviluppatore dell'adattatore (Scrounger) con una piccola donazione.",
		"es": "¿Te gusta el adaptador? Luego, apoye al desarrollador del adaptador (Scrounger) con una pequeña donación.",
		"pl": "Podoba ci się adapter? Następnie wesprzyj programistę adaptera (Scrounger) niewielką darowizną.",
		"zh-cn": "您喜欢适配器吗？然后以少量捐款支持适配器开发人员（Scrounger）。"
	},
	"script name": {
		"en": "script name",
		"de": "Skriptname",
		"ru": "Имя сценария",
		"pt": "nome do script",
		"nl": "scriptnaam",
		"fr": "nom du script",
		"it": "nome dello script",
		"es": "nombre del guion",
		"pl": "nazwa skryptu",
		"zh-cn": "脚本名称"
	},
	"generate script": {
		"en": "generate script",
		"de": "Skript generieren",
		"ru": "Создать скрипт",
		"pt": "gerar script",
		"nl": "script genereren",
		"fr": "générer un script",
		"it": "genera script",
		"es": "generar script",
		"pl": "wygeneruj skrypt",
		"zh-cn": "生成脚本"
	},
	"settings of linked object": {
		"en": "settings of linked object",
		"de": "Einstellungen des verlinkten Objekts",
		"ru": "Настройки связанного объекта",
		"pt": "configurações do objeto vinculado",
		"nl": "instellingen van gekoppeld object",
		"fr": "paramètres de l'objet lié",
		"it": "impostazioni dell'oggetto collegato",
		"es": "configuración del objeto vinculado",
		"pl": "ustawienia połączonego obiektu",
		"zh-cn": "链接对象的设置"
	},
	"name of the variable": {
		"en": "name of the variable",
		"de": "Name der Variable",
		"ru": "Имя переменной",
		"pt": "nome da variável",
		"nl": "naam van de variabele",
		"fr": "nom de la variable",
		"it": "nome della variabile",
		"es": "nombre de la variable",
		"pl": "nazwa zmiennej",
		"zh-cn": "变量的名称"
	},
	"Characters not allowed<br>Only letters and numbers are allowed": {
		"en": "Characters not allowed<br>Only letters and numbers are allowed",
		"de": "Zeichen nicht erlaubt<br>Es sind nur Buchstaben und Zahlen erlaubt",
		"ru": "Недопустимые символы<br>Разрешены только буквы и цифры",
		"pt": "Caracteres não permitidos<br>Apenas letras e números são permitidos",
		"nl": "Tekens niet toegestaan<br>Alleen letters en cijfers zijn toegestaan",
		"fr": "Caractères non autorisés<br>Seules les lettres et les chiffres sont autorisés",
		"it": "Personaggi non ammessi<br>Sono ammessi solo lettere e numeri",
		"es": "Caracteres no permitidos<br>Solo se permiten letras y números",
		"pl": "Znaki niedozwolone<br>Dozwolone są tylko litery i cyfry",
		"zh-cn": "字符不被允许<br>只允许使用字母和数字"
	},
	"include all objects of the instance": {
		"en": "include all objects of the instance",
		"de": "alle Objekte der Instanz mit einbeziehen",
		"ru": "Включить все объекты экземпляра",
		"pt": "incluir todos os objetos da instância",
		"nl": "alle objecten van het exemplaar bevatten",
		"fr": "inclure tous les objets de l'instance",
		"it": "include tutti gli oggetti dell'istanza",
		"es": "incluir todos los objetos de la instancia",
		"pl": "obejmują wszystkie obiekty instancji",
		"zh-cn": "包括实例的所有对象"
	},
	"generate setState for 'readonly' objects": {
		"en": "generate setState for 'readonly' objects",
		"de": "setState für 'readonly' Objekte generieren",
		"ru": "Создать setState для «read-only» объектов",
		"pt": "gerar setState para objetos 'readonly'",
		"nl": "setState genereren voor 'alleen-lezen' objecten",
		"fr": "générer setState pour les objets 'readonly'",
		"it": "genera setState per oggetti \"sola lettura\"",
		"es": "generar setState para objetos 'readonly'",
		"pl": "generuj setState dla obiektów „tylko do odczytu”",
		"zh-cn": "为'readonly'对象生成setState"
	},
	"more information (moment library)": {
		"en": "more information (moment library)",
		"de": "Weitere Informationen (moment library)",
		"ru": "Больше информации (moment library)",
		"pt": "mais informações (biblioteca de momentos)",
		"nl": "meer informatie (moment bibliotheek)",
		"fr": "plus d'informations (bibliothèque de moments)",
		"it": "ulteriori informazioni (libreria dei momenti)",
		"es": "más información (biblioteca de momentos)",
		"pl": "więcej informacji (biblioteka momentów)",
		"zh-cn": "更多信息（时刻库）"
	},
	"parser format": {
		"en": "parser format",
		"de": "Parser Format",
		"ru": "Формат парсера",
		"pt": "formato de analisador",
		"nl": "parser-indeling",
		"fr": "format de l'analyseur",
		"it": "formato parser",
		"es": "formato de analizador",
		"pl": "format parsera",
		"zh-cn": "解析器格式"
	},
	"do you really want to delete this link?": {
		"en": "do you really want to delete this link?",
		"de": "Möchtest du die Verlinkung wirklich löschen?",
		"ru": "Вы действительно хотите удалить эту ссылку?",
		"pt": "você realmente quer deletar esse link?",
		"nl": "wil je deze link echt verwijderen?",
		"fr": "voulez-vous vraiment supprimer ce lien?",
		"it": "vuoi veramente cancellare questo link?",
		"es": "¿De verdad quieres eliminar este enlace?",
		"pl": "czy naprawdę chcesz usunąć ten link?",
		"zh-cn": "你真的想删除这个链接吗？"
	},
	"change role '%s' in": {
		"en": "change role '%s' in",
		"de": "Ändere Rolle '%s' in",
		"ru": "Изменить роль '%s' на",
		"pt": "mudar o papel '%s' em",
		"nl": "rol '%s' in wijzigen",
		"fr": "changer le rôle '%s' dans",
		"it": "cambia il ruolo '%s' in",
		"es": "cambiar el rol '%s' en",
		"pl": "zmień rolę '%s' w",
		"zh-cn": "改变角色'％s'"
	},
	"repair": {
		"en": "repair",
		"de": "Reparatur",
		"ru": "Исправить",
		"pt": "reparar",
		"nl": "reparatie",
		"fr": "réparation",
		"it": "riparazione",
		"es": "reparar",
		"pl": "naprawic",
		"zh-cn": "修理"
	},
	"Errors have occurred, please check log file": {
		"en": "Errors have occurred, please check log file",
		"de": "Es sind Fehler aufgetreten. Überprüfen Sie die Protokolldatei",
		"ru": "Произошли ошибки, пожалуйста, проверьте файл журнала",
		"pt": "Ocorreram erros, verifique o arquivo de log",
		"nl": "Er zijn fouten opgetreden, controleer het logbestand",
		"fr": "Des erreurs se sont produites, veuillez vérifier le fichier journal",
		"it": "Si sono verificati errori, controlla il file di registro",
		"es": "Se han producido errores, verifique el archivo de registro",
		"pl": "Wystąpiły błędy, sprawdź plik dziennika",
		"zh-cn": "发生错误，请检查日志文件"
	},
	"Repair process completed successfully": {
		"en": "Repair process completed successfully",
		"de": "Reparaturvorgang erfolgreich abgeschlossen",
		"ru": "Процесс исправления успешно завершен",
		"pt": "Processo de reparo concluído com sucesso",
		"nl": "Reparatieproces succesvol afgerond",
		"fr": "Processus de réparation terminé avec succès",
		"it": "Processo di riparazione completato con successo",
		"es": "Proceso de reparación completado con éxito",
		"pl": "Proces naprawy zakończony powodzeniem",
		"zh-cn": "修复过程成功完成"
	},
	"unit": {
		"en": "unit",
		"de": "Einheit",
		"ru": "Ед. изм",
		"pt": "unidade",
		"nl": "eenheid",
		"fr": "unité",
		"it": "unità",
		"es": "unidad",
		"pl": "jednostka",
		"zh-cn": "单元"
	},
	"mergeSettingsOnRestart": {
		"en": "merge settings on adapter restart",
		"de": "Einstellungen beim Neustart des Adapters zusammenführen",
		"ru": "объединить настройки при перезагрузке адаптера",
		"pt": "mesclar configurações na reinicialização do adaptador",
		"nl": "instellingen samenvoegen bij opnieuw opstarten van de adapter",
		"fr": "fusionner les paramètres au redémarrage de l'adaptateur",
		"it": "unisci le impostazioni al riavvio dell'adattatore",
		"es": "fusionar la configuración al reiniciar el adaptador",
		"pl": "scal ustawienia po ponownym uruchomieniu adaptera",
		"zh-cn": "适配器重新启动时合并设置"
	},
	"information to create linked objects": {
		"en": "information to create linked objects",
		"de": "Informationen zum Erstellen verknüpfter Objekte",
		"ru": "информация для создания связанных объектов",
		"pt": "informações para criar objetos vinculados",
		"nl": "informatie om gekoppelde objecten te maken",
		"fr": "informations pour créer des objets liés",
		"it": "informazioni per creare oggetti collegati",
		"es": "información para crear objetos vinculados",
		"pl": "informacje do tworzenia połączonych obiektów",
		"zh-cn": "创建链接对象的信息"
	},
	"Documentations": {
		"en": "Documentations",
		"de": "Dokumentationen",
		"ru": "Документация",
		"pt": "Documentações",
		"nl": "Documentaties",
		"fr": "Documentations",
		"it": "Documentazioni",
		"es": "Documentaciones",
		"pl": "Dokumentacje",
		"zh-cn": "文件资料"
	},
	"doc_adapter_settings": {
		"en": "adapter settings",
		"de": "Adaptereinstellungen",
		"ru": "настройки адаптера",
		"pt": "configurações do adaptador",
		"nl": "adapter instellingen",
		"fr": "paramètres de l'adaptateur",
		"it": "impostazioni dell'adattatore",
		"es": "configuración del adaptador",
		"pl": "ustawienia adaptera",
		"zh-cn": "适配器设置"
	},
	"doc_forum": {
		"en": "Forum",
		"de": "Forum",
		"ru": "Форум",
		"pt": "Fórum",
		"nl": "Forum",
		"fr": "Forum",
		"it": "Forum",
		"es": "Foro",
		"pl": "Forum",
		"zh-cn": "论坛"
	},
	"settings": {
		"en": "settings",
		"de": "Einstellungen",
		"ru": "настройки",
		"pt": "definições",
		"nl": "instellingen",
		"fr": "réglages",
		"it": "impostazioni",
		"es": "ajustes",
		"pl": "ustawienia",
		"zh-cn": "设定"
	},
	"prefix_as_name": {
		"en": "prefix as name",
		"de": "Präfix als Name",
		"ru": "префикс как имя",
		"pt": "prefixo como nome",
		"nl": "prefix als naam",
		"fr": "préfixe comme nom",
		"it": "prefisso come nome",
		"es": "prefijo como nombre",
		"pl": "prefiks jako nazwa",
		"zh-cn": "前缀作为名称"
	},
	"id_as_name": {
		"en": "id as name",
		"de": "ID als Name",
		"ru": "id как имя",
		"pt": "id como nome",
		"nl": "id als naam",
		"fr": "id comme nom",
		"it": "id come nome",
		"es": "id como nombre",
		"pl": "id jako nazwa",
		"zh-cn": "id作为名字"
	},
	"parent name": {
		"en": "name of object which is linked with",
		"de": "Name des Objekts, mit dem verlinkt ist",
		"ru": "имя объекта, который связан с",
		"pt": "nome do objeto que está ligado a",
		"nl": "naam van het object waarmee is verbonden",
		"fr": "nom de l'objet lié à",
		"it": "nome dell'oggetto a cui è collegato",
		"es": "nombre del objeto que está vinculado con",
		"pl": "nazwa obiektu, z którym jest powiązany",
		"zh-cn": "与之链接的对象的名称"
	},
	"SelectJavascriptInstance": {
		"en": "Javascript Instance",
		"de": "Javascript Instanz",
		"ru": "Экземпляр Javascript",
		"pt": "Instância Javascript",
		"nl": "Javascript-instantie",
		"fr": "Instance Javascript",
		"it": "Istanza Javascript",
		"es": "Instancia de Javascript",
		"pl": "Instancja JavaScript",
		"zh-cn": "JavaScript实例"
	},
	"not installed": {
		"en": "not installed",
		"de": "nicht installiert",
		"ru": "не установлено",
		"pt": "não instalado",
		"nl": "niet geïnstalleerd",
		"fr": "pas installé",
		"it": "non installato",
		"es": "no instalado",
		"pl": "nie zainstalowany",
		"zh-cn": "未安装"
	},
	"prefixFromFunctionOrRoom": {
		"en": "Function and room",
		"de": "Funktion und Raum",
		"ru": "Функция и комната",
		"pt": "Função e sala",
		"nl": "Functie en ruimte",
		"fr": "Fonction et pièce",
		"it": "Funzione e spazio",
		"es": "Función y sala",
		"pl": "Funkcja i pomieszczenie",
		"zh-cn": "功能和房间"
	},
	"createPrefixFromFunctionOrRoom": {
		"en": "use function and room to create automatically prefix for id",
		"de": "Funktion und Raum verwenden, um automatisch ein Präfix für die ID zu erstellen",
		"ru": "используйте функцию и место для автоматического создания префикса для идентификатора",
		"pt": "use função e espaço para criar prefixo automático para id",
		"nl": "gebruik functie en ruimte om automatisch een prefix voor id te maken",
		"fr": "utiliser la fonction et la pièce pour créer automatiquement un préfixe pour l'id",
		"it": "usa funzione e room per creare automaticamente il prefisso per id",
		"es": "use la función y el espacio para crear automáticamente el prefijo para la identificación",
		"pl": "użyj funkcji i pomieszczenia, aby automatycznie utworzyć prefiks dla identyfikatora",
		"zh-cn": "使用功能和空间为ID自动创建前缀"
	},
	"usePrefixAsName": {
		"en": "use prefix for id automatically as name",
		"de": "Automatisch das Präfix für die ID als Namen verwenden",
		"ru": "использовать префикс для идентификатора автоматически в качестве имени",
		"pt": "use prefixo para id automaticamente como nome",
		"nl": "gebruik prefix voor id automatisch als naam",
		"fr": "utiliser automatiquement le préfixe pour l'identifiant comme nom",
		"it": "usa automaticamente il prefisso per id come nome",
		"es": "use el prefijo para la identificación automáticamente como nombre",
		"pl": "użyj prefiksu dla id automatycznie jako nazwa",
		"zh-cn": "将id的前缀自动用作名称"
	},
	"includeIdAlsoInName": {
		"en": "include id for automatic names",
		"de": "ID für automatischen Namen mit einbeziehen",
		"ru": "включить идентификатор для автоматических имен",
		"pt": "incluir id para nomes automáticos",
		"nl": "inclusief id voor automatische namen",
		"fr": "inclure l'ID pour les noms automatiques",
		"it": "includi l'ID per i nomi automatici",
		"es": "incluir id para nombres automáticos",
		"pl": "dołącz identyfikator dla nazw automatycznych",
		"zh-cn": "包含自动名称的ID"
	},
	"Settings can only be made for individual datapoints!": {
		"en": "Settings can only be made for individual datapoints!",
		"de": "Einstellungen können nur für einzelne Datenpunkte vorgenommen werden!",
		"ru": "Настройки могут быть выполнены только для отдельных точек данных!",
		"pt": "As configurações só podem ser feitas para pontos de dados individuais!",
		"nl": "Instellingen zijn alleen mogelijk voor individuele datapunten!",
		"fr": "Les réglages ne peuvent être effectués que pour des points de données individuels!",
		"it": "Le impostazioni possono essere effettuate solo per singoli datapoint!",
		"es": "¡Solo se pueden realizar ajustes para puntos de datos individuales!",
		"pl": "Ustawienia można wprowadzać tylko dla pojedynczych punktów danych!",
		"zh-cn": "只能为单个数据点进行设置！"
	},
	"boolean_invert": {
		"en": "invert boolean",
		"de": "Logikwert umkehren",
		"ru": "инвертировать логическое значение",
		"pt": "inverter booleano",
		"nl": "omkeren boolean",
		"fr": "inverser booléen",
		"it": "invertire booleano",
		"es": "invertir booleano",
		"pl": "invert boolean",
		"zh-cn": "反转布尔"
	}
};
