/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"linkeddevices adapter settings": {
		"en": "Adapter settings for linkeddevices",
		"de": "Adaptereinstellungen für linkeddevices",
		"ru": "Настройки адаптера для linkeddevices",
		"pt": "Configurações do adaptador para linkeddevices",
		"nl": "Adapterinstellingen voor linkeddevices",
		"fr": "Paramètres d'adaptateur pour linkeddevices",
		"it": "Impostazioni dell'adattatore per linkeddevices",
		"es": "Ajustes del adaptador para linkeddevices",
		"pl": "Ustawienia adaptera dla linkeddevices",
		"zh-cn": "linkeddevices的适配器设置"
	},
	"notDeleteDeadLinkedObjects": {
		"en": "Do not delete objects that are no longer linked",
		"de": "Nicht mehr verlinkte Objekte nicht löschen",
		"ru": "option1",
		"pt": "option1",
		"nl": "option1",
		"fr": "option1",
		"it": "option1",
		"es": "option1",
		"pl": "option1",
		"zh-cn": "option1"
	},
	"option2": {
		"en": "option2",
		"de": "option2",
		"ru": "option2",
		"pt": "option2",
		"nl": "option2",
		"fr": "option2",
		"it": "option2",
		"es": "option2",
		"pl": "option2",
		"zh-cn": "option2"
	},
	"composite id of linked object": {
		"en": "composite id of linked object",
		"de": "Zusammengesetze Id des verlinkten Objektes",
		"ru": "составной идентификатор связанного объекта",
		"pt": "ID composta do objeto vinculado",
		"nl": "samengestelde ID van gekoppeld object",
		"fr": "ID composite d'objet lié",
		"it": "ID composito dell'oggetto collegato",
		"es": "ID compuesto del objeto vinculado",
		"pl": "id złożony połączonego obiektu",
		"zh-cn": "链接对象的复合id"
	},
	"name of linked object": {
		"en": "name of linked object",
		"de": "Name des verlinkten Objekts",
		"ru": "название связанного объекта",
		"pt": "nome do objeto vinculado",
		"nl": "naam van gekoppeld object",
		"fr": "nom de l'objet lié",
		"it": "nome dell'oggetto collegato",
		"es": "nombre del objeto vinculado",
		"pl": "nazwa połączonego obiektu",
		"zh-cn": "链接对象的名称"
	},
	"is linked": {
		"en": "is linked",
		"de": "verlinkt",
		"ru": "связан",
		"pt": "está associado",
		"nl": "is gelinkt",
		"fr": "est lié",
		"it": "è collegato",
		"es": "está vinculado",
		"pl": "jest połączone",
		"zh-cn": "已连接"
	},
	"linked with": {
		"en": "linked with",
		"de": "verlinkt mit",
		"ru": "связан с",
		"pt": "ligado com",
		"nl": "gelinkt met",
		"fr": "lié à",
		"it": "collegato con",
		"es": "Vinculado con",
		"pl": "połączony z",
		"zh-cn": "与连接"
	},
	"expert settings for linked object with type '%s'": {
		"en": "expert settings for linked object with type '%s'",
		"de": "Experteneinstellungen für verlinktes Objekt vom Typ '%s'",
		"ru": "экспертные настройки для связанного объекта с типом '%s'",
		"pt": "configurações de especialista para objeto vinculado com o tipo '%s'",
		"nl": "expertinstellingen voor gekoppeld object met type '%s'",
		"fr": "paramètres experts pour un objet lié de type '%s'",
		"it": "impostazioni avanzate per l'oggetto collegato con tipo '%s'",
		"es": "Configuraciones expertas para objetos vinculados con tipo '%s'",
		"pl": "ustawienia eksperckie dla obiektu połączonego z typem '%s'",
		"zh-cn": "类型为'%s'的链接对象的专家设置"
	},
	"change unit '%s' to": {
		"en": "change unit '%s' to",
		"de": "Ändere Einheit '%s' in",
		"ru": "измените единицу измерения %s на",
		"pt": "mudar a unidade '%s' para",
		"nl": "verander eenheid '%s' in",
		"fr": "remplacez l'unité '%s' par",
		"it": "cambia unità '%s' a",
		"es": "cambia la unidad '%s' a",
		"pl": "zmień jednostkę „%s” na",
		"zh-cn": "将单位“%s”更改为"
	},
	"prefix for id of linked object": {
		"en": "prefix for id of linked object",
		"de": "Präfix für ID des verlinkten Objektes",
		"ru": "префикс для идентификатора связанного объекта",
		"pt": "prefixo para id do objeto vinculado",
		"nl": "voorvoegsel voor id van gekoppeld object",
		"fr": "préfixe pour l'identifiant de l'objet lié",
		"it": "prefisso per l'id dell'oggetto collegato",
		"es": "prefijo para id del objeto vinculado",
		"pl": "prefiks dla id połączonego obiektu",
		"zh-cn": "链接对象的id的前缀"
	},
	"id of linked object": {
		"en": "id of linked object",
		"de": "ID des verlinkten Objekts",
		"ru": "идентификатор связанного объекта",
		"pt": "ID do objeto vinculado",
		"nl": "id van gekoppeld object",
		"fr": "id de l'objet lié",
		"it": "id di oggetto collegato",
		"es": "Id del objeto vinculado",
		"pl": "id połączonego obiektu",
		"zh-cn": "链接对象的id"
	},
	"only numbers and math operators allowed for read only object": {
		"en": "not allowed signs!<br>Only numbers an math operatorsare allowed! Input must start with math operator.<br><br>Allowed operators: + - / * , . ( )",
		"de": "Zeichen nicht erlaubt! <br> Nur Zahlen und mathematische Operatoren sind erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen. <br> <br> Zulässige Operatoren: + - / *,. ()",
		"ru": "запрещенные знаки! <br> Разрешены только цифры и математические операторы! Ввод должен начинаться с математического оператора. <br> <br> Допустимые операторы: + - / *,. ()",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos são permitidos! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: + - / *,. ()",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators zijn toegestaan! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: + - / *,. ()",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés! La saisie doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: + - / *,. ()",
		"it": "segni non consentiti! <br> Sono consentiti solo numeri e operatori matematici! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: + - / *,. ()",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten operadores de números y matemáticas! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: + - / *,. ()",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne są dozwolone! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: + - / *,. ()",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符！输入必须以数学运算符开头。<br> <br>允许的运算符：+  -  / * ,. （）"
	},
	"only numbers and math operators allowed": {
		"en": "not allowed signs!<br>Only numbers an math operatorsare allowed! Input must start with math operator.<br><br>Allowed operators: / * , .",
		"de": "Zeichen nicht erlaubt! <br> Nur Zahlen und mathematische Operatoren sind erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen. <br> <br> Zulässige Operatoren: / *,.",
		"ru": "запрещенные знаки! <br> Разрешены только цифры и математические операторы! Ввод должен начинаться с математического оператора. <br> <br> Разрешенные операторы: / *,.",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos são permitidos! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: / *,.",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators zijn toegestaan! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: / *,.",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés! La saisie doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: / *,.",
		"it": "segni non consentiti! <br> Sono consentiti solo numeri e operatori matematici! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: / *,.",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten operadores de números y matemáticas! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: / *,.",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne są dozwolone! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: / *,.",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符！输入必须以数学运算符开头。<br> <br>允许的运算符：/ * ,."
	},
	"max. number of decimal places": {
		"en": "max. number of decimal places",
		"de": "max. Anzahl der Nachkommastellen",
		"ru": "Максимум. количество знаков после запятой",
		"pt": "max. número de casas decimais",
		"nl": "max. aantal decimalen",
		"fr": "max. nombre de décimales",
		"it": "max. numero di cifre decimali",
		"es": "max. número de decimales",
		"pl": "max. liczba miejsc dziesiętnych",
		"zh-cn": "最大。小数位数"
	},
	"only numbers allowed": {
		"en": "only numbers allowed",
		"de": "Nur Nummern sind als Eingabe erlaubt!",
		"ru": "разрешены только цифры",
		"pt": "somente números permitidos",
		"nl": "alleen cijfers toegestaan",
		"fr": "seuls les nombres autorisés",
		"it": "solo numeri consentiti",
		"es": "solo números permitidos",
		"pl": "dozwolone są tylko liczby",
		"zh-cn": "只允许数字"
	},
	"calculation for 'read' object": {
		"en": "calculation for 'read' object",
		"de": "Umrechnung für verlinktes 'read' Objekt",
		"ru": "расчет для «прочитанного» объекта",
		"pt": "cálculo para objeto 'read'",
		"nl": "berekening voor 'lees' object",
		"fr": "calcul pour objet 'lu'",
		"it": "calcolo per oggetto 'lettura'",
		"es": "cálculo para el objeto 'leer'",
		"pl": "obliczanie obiektu „czytaj”",
		"zh-cn": "计算'读'对象"
	},
	"calculation for linked object": {
		"en": "calculation for linked object",
		"de": "Umrechnung für verlinktes Objekt",
		"ru": "расчет для связанного объекта",
		"pt": "cálculo para objeto vinculado",
		"nl": "berekening voor gekoppeld object",
		"fr": "calcul pour objet lié",
		"it": "calcolo per oggetto collegato",
		"es": "cálculo para objeto vinculado",
		"pl": "obliczenia dla połączonego obiektu",
		"zh-cn": "链接对象的计算"
	},
	"number": {
		"en": "number",
		"de": "Zahl",
		"ru": "Число",
		"pt": "número",
		"nl": "getal",
		"fr": "nombre",
		"it": "Numero",
		"es": "numero",
		"pl": "numer",
		"zh-cn": "数"
	},
	"not allowed chars for Id": {
		"en": "not allowed chars for Id!<br><br>Not Allowed chars: * ? \" ' [ ]",
		"de": "Nicht erlaubte Zeichen für Id!<br><br>Nicht erlaubte Zeichen: * ? \" ' [ ]",
		"ru": "запрещенные символы для идентификатора! <br> <br> Недопустимые символы: *? \\ \"'[]",
		"pt": "não permitido chars para Id! <br> <br> Não é permitido chars: *? \\ \"'[]",
		"nl": "niet toegestane tekens voor ID! <br> <br> Niet toegestaan ​​tekens: *? \\ \"'[]",
		"fr": "caractères non autorisés pour Id! <br> <br> Caractères non autorisés: *? \\ \"'[]",
		"it": "caratteri non consentiti per ID! <br> <br> Caratteri non consentiti: *? \\ \"'[]",
		"es": "caracteres no permitidos para Id! <br> <br> caracteres no permitidos: *? \\ \"'[]",
		"pl": "niedozwolone znaki dla Id! <br> <br> Nie dozwolone znaki: *? „” []",
		"zh-cn": "id不允许使用字符！<br> <br>不允许使用字符：*？ \\''[]"
	},
	"do not convert": {
		"en": "do not convert",
		"de": "nicht umwandeln",
		"ru": "не конвертировать",
		"pt": "não converter",
		"nl": "niet converteren",
		"fr": "ne pas convertir",
		"it": "non convertire",
		"es": "no convertir",
		"pl": "nie konwertuj",
		"zh-cn": "不要转换"
	},
	"convert linked object to type": {
		"en": "convert to type",
		"de": "Konvertiere in Typ",
		"ru": "преобразовать в тип",
		"pt": "converter em tipo",
		"nl": "converteren naar type",
		"fr": "convertir en type",
		"it": "convertire in tipo",
		"es": "convertir a tipo",
		"pl": "przekonwertować na typ",
		"zh-cn": "转换为类型"
	},
	"condition 'true' for linked object": {
		"en": "condition 'true' for linked object",
		"de": "Bedingung 'true' für verlinktes Objekt",
		"ru": "условие 'true' для связанного объекта",
		"pt": "condição 'true' para objeto vinculado",
		"nl": "voorwaarde 'waar' voor gekoppeld object",
		"fr": "condition 'true' pour objet lié",
		"it": "condizione 'true' per oggetto collegato",
		"es": "Condición 'true' para objeto vinculado",
		"pl": "warunek „prawda” dla połączonego obiektu",
		"zh-cn": "条件'true'表示链接对象"
	},
	"value if linked object is 'true'": {
		"en": "value if linked object is 'true'",
		"de": "Wert wenn verlinktes Objekt 'true' ist",
		"ru": "значение, если связанный объект равен 'true'",
		"pt": "valor se o objeto vinculado for 'verdadeiro'",
		"nl": "waarde als gekoppeld object 'waar' is",
		"fr": "valeur si l'objet lié est 'true'",
		"it": "valore se l'oggetto collegato è 'vero'",
		"es": "valor si el objeto vinculado es 'verdadero'",
		"pl": "wartość, jeśli powiązany obiekt jest „prawdziwy”",
		"zh-cn": "链接对象为'true'时的值"
	},
	"value if linked object is 'false'": {
		"en": "value if linked object is 'false'",
		"de": "Wert wenn verlinktes Objekt 'false' ist",
		"ru": "значение, если связанный объект имеет значение «ложь»",
		"pt": "valor se o objeto vinculado for 'falso'",
		"nl": "waarde als gekoppeld object 'false' is",
		"fr": "valeur si l'objet lié est 'false'",
		"it": "valore se l'oggetto collegato è 'falso'",
		"es": "valor si el objeto vinculado es 'falso'",
		"pl": "wartość, jeśli połączony obiekt jest „fałszywy”",
		"zh-cn": "链接对象为'false'时的值"
	},
	"change min '%s' to": {
		"en": "change min '%s' to",
		"de": "Ändere min '%s' in",
		"ru": "измените min '%s' на",
		"pt": "altere min '%s' para",
		"nl": "verander min '%s' in",
		"fr": "remplacez min '%s' par",
		"it": "cambia min '%s' in",
		"es": "cambiar min '%s' a",
		"pl": "zmień min '%s' na",
		"zh-cn": "将min'％s'更改为"
	},
	"change max '%s' to": {
		"en": "change max '%s' to",
		"de": "Ändere max '%s' auf",
		"ru": "изменить максимум \"% s\" на",
		"pt": "altere max '%s' para",
		"nl": "verander max '%s' in",
		"fr": "remplacez max '%s' par",
		"it": "modifica max '%s' a",
		"es": "cambiar max '%s' a",
		"pl": "zmień max '%s' na",
		"zh-cn": "将max'％s'更改为"
	},
	"only numbers and mathematical operators allowed as a condition": {
		"en": "not allowed signs!<br>Only numbers and mathematical operators allowed as a condition! Input must start with math operator.<br><br>Allowed operators: = != > < >= <=",
		"de": "Zeichen nicht erlaubt!<br>Nur Zahlen und mathematische Operatoren als Bedingung erlaubt! Die Eingabe muss mit einem mathematischen Operator beginnen.<br><br>Zulässige Operatoren: = != > < >= <=",
		"ru": "запрещенные знаки! <br> В качестве условия допускаются только числа и математические операторы! Ввод должен начинаться с математического оператора. <br> <br> Разрешенные операторы: =! => <> = <=",
		"pt": "Sinais não permitidos! <br> Somente números e operadores matemáticos permitidos como condição! A entrada deve começar com o operador de matemática. <br> <br> Operadores permitidos: =! => <> = <=",
		"nl": "geen toegestane tekens! <br> Alleen getallen en wiskundige operators toegestaan ​​als voorwaarde! Input moet beginnen met wiskundige operator. <br> <br> Toegestane operators: =! => <> = <=",
		"fr": "signes non autorisés! <br> Seuls les nombres et les opérateurs mathématiques sont autorisés comme condition! L'entrée doit commencer par un opérateur mathématique. <br> <br> Opérateurs autorisés: =! => <> = <=",
		"it": "segni non consentiti! <br> Solo numeri e operatori matematici ammessi come condizione! L'input deve iniziare con l'operatore matematico. <br> <br> Operatori consentiti: =! => <> = <=",
		"es": "¡Signos no permitidos! <br> ¡Sólo se permiten números y operadores matemáticos como condición! La entrada debe comenzar con el operador matemático. <br> <br> Operadores permitidos: =! => <> = <=",
		"pl": "niedozwolone znaki! <br> Tylko liczby i operatory matematyczne dozwolone jako warunek! Wejście musi zaczynać się od operatora matematycznego. <br> <br> Dozwolone operatory: =! => <> = <=",
		"zh-cn": "不允许的标志！<br>只允许数字和数学运算符作为条件！输入必须以数学运算符开头。<br> <br>允许的运算符：=！=> <> = <="
	},
	"conditions string": {
		"en": "conditions string",
		"de": "Zeichenkette mit Bedingungen",
		"ru": "строка условий",
		"pt": "condições de string",
		"nl": "voorwaarden string",
		"fr": "conditions chaîne",
		"it": "stringa di condizioni",
		"es": "cadena de condiciones",
		"pl": "warunki ciąg",
		"zh-cn": "条件字符串"
	},
	"conditions multi": {
		"en": "conditions multi",
		"de": "Werteliste mit Bedingungen",
		"ru": "условия мульти",
		"pt": "condições multi",
		"nl": "voorwaarden multi",
		"fr": "conditions multi",
		"it": "condizioni multi",
		"es": "condiciones multi",
		"pl": "warunki multi",
		"zh-cn": "条件多"
	},
	"string": {
		"en": "string",
		"de": "Zeichenkette",
		"ru": "Строка",
		"pt": "string",
		"nl": "Tekenreeks",
		"fr": "chaîne",
		"it": "stringa",
		"es": "cadena de caracteres",
		"pl": "strunowy",
		"zh-cn": "串"
	},
	"boolean": {
		"en": "boolean",
		"de": "Logikwert",
		"ru": "Логическая переменная",
		"pt": "valor lógico",
		"nl": "boolean",
		"fr": "booléen",
		"it": "Booleano",
		"es": "booleano",
		"pl": "boolean",
		"zh-cn": "布尔"
	},
	"multi": {
		"en": "multistate",
		"de": "Werteliste",
		"ru": "Перечисление",
		"pt": "lista de valores",
		"nl": "waardenlijst",
		"fr": "liste de valeurs",
		"it": "Multistate",
		"es": "lista de valores",
		"pl": "multistate",
		"zh-cn": "多态"
	},
	"enabled": {
		"en": "enabled",
		"de": "Aktiviert",
		"ru": "активно",
		"pt": "ativado",
		"nl": "ingeschakeld",
		"fr": "activée",
		"it": "abilitato",
		"es": "activado",
		"pl": "włączony",
		"zh-cn": "启用"
	},
	"active": {
		"en": "active",
		"de": "aktiv",
		"ru": "активно",
		"pt": "ativo",
		"nl": "actief",
		"fr": "actif",
		"it": "Attivo",
		"es": "activo",
		"pl": "aktywny",
		"zh-cn": "激活"
	},
	"Cancel": {
		"en": "Cancel",
		"de": "Abbrechen",
		"ru": "Отмена",
		"pt": "Cancelar",
		"nl": "Annuleren",
		"fr": "Annuler",
		"it": "Annulla",
		"es": "Cancelar",
		"pl": "Anuluj",
		"zh-cn": "取消"
	},
	"Settings": {
		"en": "Settings",
		"de": "Einstellungen",
		"ru": "Настройки",
		"pt": "Configurações",
		"nl": "instellingen",
		"fr": "Paramètres",
		"it": "impostazioni",
		"es": "Configuración",
		"pl": "Ustawienia",
		"zh-cn": "设置"
	},
	"Settings for %s": {
		"en": "Settings for %s",
		"de": "Einstellungen für %s",
		"ru": "Настройки для %s",
		"pt": "Configurações para %s",
		"nl": "Instellingen voor %s",
		"fr": "Paramètres pour %s",
		"it": "Impostazioni per %s",
		"es": "Configuraciones para %s",
		"pl": "Ustawienia dla %s",
		"zh-cn": "%s的设置"
	},
	"Storage of %s": {
		"en": "Storage of <span class=\"name\">%s</span>",
		"de": "Einstellungen von <span class=\"name\">%s</span>",
		"ru": "Настройки для <span class=\"name\">%s</span>",
		"pt": "História de <span class=\"name\">%s</span>",
		"nl": "Opslag van <span class=\"name\">%s</span>",
		"fr": "Stockage de <span class=\"name\">%s</span>",
		"it": "Memorizzazione di %s",
		"es": "Configuraciones de <span class=\"name\">%s</span>",
		"pl": "Przechowywanie <span class=\"name\"> %s </span>",
		"zh-cn": "存储<span class=\"name\">%s</span>"
	},
	"Save": {
		"en": "Save",
		"de": "Speichern",
		"ru": "Сохранить",
		"pt": "Gravar",
		"nl": "Opslaan",
		"fr": "sauvegarder",
		"it": "Salvare",
		"es": "Grabar",
		"pl": "Zapisać",
		"zh-cn": "保存"
	},
	"Table": {
		"en": "Table",
		"de": "Tabelle",
		"ru": "Таблица",
		"pt": "Tabela",
		"nl": "Tabel",
		"fr": "Table",
		"it": "tabella",
		"es": "Tabla",
		"pl": "Stół",
		"zh-cn": "表"
	},
	"Chart": {
		"en": "Chart",
		"de": "Grafik",
		"ru": "График",
		"pt": "Gráfico",
		"nl": "tabel",
		"fr": "Graphique",
		"it": "diagramma",
		"es": "Gráfico",
		"pl": "Wykres",
		"zh-cn": "图表"
	},
	"Are you sure? Changes are not saved.": {
		"en": "Are you sure? Changes are not saved.",
		"de": "Sind Sie sicher? Die Änderungen sind nicht gespeichert.",
		"ru": "Изменения не сохранены. Всё равно закрыть?",
		"pt": "Você tem certeza? As alterações não estão gravadas.",
		"nl": "Weet je het zeker? Wijzigingen worden niet opgeslagen.",
		"fr": "Êtes-vous sûr? Les modifications ne sont pas enregistrées.",
		"it": "Sei sicuro? Le modifiche non verranno salvate.",
		"es": "¿Estás seguro? Los cambios no se guardan.",
		"pl": "Jesteś pewny? Zmiany nie są zapisywane.",
		"zh-cn": "你确定吗？更改未保存。"
	},
	"Please confirm": {
		"en": "Please confirm",
		"de": "Bitte bestätigen",
		"ru": "Пожалуйста подтвердите",
		"pt": "Por favor confirme",
		"nl": "Bevestig alstublieft",
		"fr": "Veuillez confirmer",
		"it": "Si prega di confermare",
		"es": "Por favor, confirme",
		"pl": "Proszę potwierdzić", "zh-cn": "请确认"
	},
	"value if object is 'true'": {
		"en": "value if object is 'true'",
		"de": "Wert wenn Objekt 'true' ist",
		"ru": "значение, если объект равен 'true'",
		"pt": "valor se o objeto for 'verdadeiro'",
		"nl": "waarde als object 'waar' is",
		"fr": "valeur si l'objet est 'true'",
		"it": "valore se l'oggetto è 'vero'",
		"es": "valor si el objeto es 'verdadero'",
		"pl": "wartość, jeśli obiekt jest „prawdziwy”",
		"zh-cn": "对象为'true'时的值"
	},
	"value if object is 'false'": {
		"en": "value if object is 'false'",
		"de": "Wert wenn Objekt 'false' ist",
		"ru": "значение, если объект «ложь»",
		"pt": "valor se o objeto for 'falso'",
		"nl": "waarde als object 'false' is",
		"fr": "valeur si l'objet est 'false'",
		"it": "valore se l'oggetto è 'falso'",
		"es": "valor si el objeto es 'falso'",
		"pl": "wartość, jeśli obiekt jest „fałszywy”",
		"zh-cn": "对象为'false'时的值"
	},
	"settings can only be adjusted in the object to which it is linked!": {
		"en": "settings can only be adjusted in the object to which it is linked!",
		"de": "Einstellungen können nur in dem Objekt vorgenommen werden, mit dem es verlinkt ist!",
		"ru": "Настройки можно настроить только в том объекте, с которым он связан!",
		"pt": "configurações só podem ser ajustadas no objeto ao qual está vinculado!",
		"nl": "instellingen kunnen alleen worden aangepast in het object waaraan het is gekoppeld!",
		"fr": "les réglages ne peuvent être ajustés que dans l'objet auquel il est lié!",
		"it": "le impostazioni possono essere modificate solo nell'oggetto a cui è collegato!",
		"es": "La configuración solo se puede ajustar en el objeto al que está vinculado.",
		"pl": "ustawienia można regulować tylko w obiekcie, z którym jest połączony!",
		"zh-cn": "设置只能在与其链接的对象中进行调整！"
	},
	"Select": {
		"en": "Select",
		"de": "Auswählen",
		"ru": "Выбрать",
		"pt": "Selecione",
		"nl": "kiezen",
		"fr": "Sélectionner",
		"it": "Selezionare",
		"es": "Seleccione",
		"pl": "Wybierz",
		"zh-cn": "选择"
	},
	"assign link": {
		"en": "assign link",
		"de": "Link zuweisen",
		"ru": "назначить ссылку",
		"pt": "atribuir link",
		"nl": "link toewijzen",
		"fr": "attribuer un lien",
		"it": "assegna il collegamento",
		"es": "asignar enlace",
		"pl": "przypisz link",
		"zh-cn": "分配链接"
	},
	"Overview of all linked objects": {
		"en": "Overview of all linked objects",
		"de": "Übersicht aller verlinkten Objekte",
		"ru": "Обзор всех связанных объектов",
		"pt": "Visão geral de todos os objetos vinculados",
		"nl": "Overzicht van alle gekoppelde objecten",
		"fr": "Vue d'ensemble de tous les objets liés",
		"it": "Panoramica di tutti gli oggetti collegati",
		"es": "Resumen de todos los objetos vinculados",
		"pl": "Przegląd wszystkich połączonych obiektów",
		"zh-cn": "所有链接对象的概述"
	},
	"name": {
		"en": "name",
		"de": "Name",
		"ru": "Имя",
		"pt": "nome",
		"nl": "Naam",
		"fr": "prénom",
		"it": "nome",
		"es": "nome",
		"pl": "Nazwa",
		"zh-cn": "名称"
	},
	"browse the table": {
		"en": "browse the table",
		"de": "Tabelle durchsuchen",
		"ru": "просмотреть таблицу",
		"pt": "navegue pela mesa",
		"nl": "blader door de tafel",
		"fr": "parcourir la table",
		"it": "sfoglia il tavolo",
		"es": "navegar por la mesa",
		"pl": "przeglądaj stół",
		"zh-cn": "浏览表格"
	},
	"link to an already linked object of the same instance is not possible!": {
		"en": "link to an already linked object of the same instance is not possible!",
		"de": "Eine Verlinkung zu einem bereits verlinkten Objekt derselben Instanz ist nicht möglich!",
		"ru": "ссылка на уже связанный объект того же экземпляра невозможна!",
		"pt": "link para um objeto já vinculado da mesma instância não é possível!",
		"nl": "link naar een reeds gekoppeld object van dezelfde instantie is niet mogelijk!",
		"fr": "un lien vers un objet déjà lié de la même instance n'est pas possible!",
		"it": "il collegamento a un oggetto già collegato della stessa istanza non è possibile!",
		"es": "¡El enlace a un objeto ya enlazado de la misma instancia no es posible!",
		"pl": "link do już połączonego obiektu tej samej instancji nie jest możliwy!",
		"zh-cn": "链接到同一实例的已链接对象是不可能的！"
	},
	"the selected object is already linked with '%s'!": {
		"en": "the selected object is already linked with '%s'!",
		"de": "das ausgewählte Objekt ist bereits mit '%s' verlinkt!",
		"ru": "выбранный объект уже связан с ''%s'!",
		"pt": "o objeto selecionado já está vinculado a '%s'!",
		"nl": "het geselecteerde object is al gekoppeld aan '%s'!",
		"fr": "l'objet sélectionné est déjà lié à '%s'!",
		"it": "l'oggetto selezionato è già collegato con '%s'!",
		"es": "el objeto seleccionado ya está vinculado con '%s'!",
		"pl": "wybrany obiekt jest już powiązany z '%s'!",
		"zh-cn": "所选对象已与'％s'链接!"
	},
	"the selected object is of type '%s'.<br>The linked object needs an object of type '%s'!": {
		"en": "the selected object is of type '%s'.<br>The linked object needs an object of type '%s'!",
		"de": "Das ausgewählte Objekt ist vom Typ '%s'.<br>Das verlinkte Objekt benötigt aber ein Objekt vom Typ '%s'!",
		"ru": "выбранный объект имеет тип '%s' \"'.<br>Связанному объекту нужен объект типа '%s'!",
		"pt": "o objeto selecionado é do tipo '%s'.<br>O objeto vinculado precisa de um objeto do tipo '%s'!",
		"nl": "het geselecteerde object is van het type '%s'.<br>Het gekoppelde object heeft een object van het type '%s' nodig!",
		"fr": "l'objet sélectionné est de type '%s'.<br>L'objet lié a besoin d'un objet de type '%s'!",
		"it": "l'oggetto selezionato è di tipo '%s'.<br>L'oggetto collegato ha bisogno di un oggetto di tipo '%s'!",
		"es": "El objeto seleccionado es de tipo '%s'.<br>El objeto vinculado necesita un objeto de tipo '%s'!",
		"pl": "wybrany obiekt jest typu '%s'.<br>Połączony obiekt potrzebuje obiektu typu '%s'!",
		"zh-cn": "所选对象的类型为'％s'。链接对象需要一个'％s'类型的对象！"
	},
	"Error": {
		"en": "Error",
		"de": "Fehler",
		"ru": "Ошибка",
		"pt": "Erro",
		"nl": "Fout",
		"fr": "Erreur",
		"it": "Errore",
		"es": "Error",
		"pl": "Błąd",
		"zh-cn": "错误"
	},
	"Via 'Settings' button in the menu 'Object' you can create a new linked object.": {
		"en": "Via 'Settings' button in the menu 'Object' you can create a new linked object.",
		"de": "Über die Schaltfläche 'Einstellungen' im Menü 'Objekt' können Sie ein neues verlinktes Objekt erstellen.",
		"ru": "С помощью кнопки «Настройки» в меню «Объект» вы можете создать новый связанный объект.",
		"pt": "Através do botão 'Configurações' no menu 'Objeto' você pode criar um novo objeto vinculado.",
		"nl": "Via de knop 'Instellingen' in het menu 'Object' kunt u een nieuw gekoppeld object maken.",
		"fr": "Via le bouton 'Paramètres' du menu 'Objet', vous pouvez créer un nouvel objet lié.",
		"it": "Tramite il pulsante \"Impostazioni\" nel menu \"Oggetto\" è possibile creare un nuovo oggetto collegato.",
		"es": "A través del botón 'Configuración' en el menú 'Objeto' puede crear un nuevo objeto vinculado.",
		"pl": "Za pomocą przycisku „Ustawienia” w menu „Obiekt” możesz utworzyć nowy połączony obiekt.",
		"zh-cn": "通过菜单“对象”中的“设置”按钮，您可以创建新的链接对象。"
	  }
};